# SPDX-FileCopyrightText: 2024 Niklas Wimmer <mail@nwimmer.me>
# SPDX-License-Identifier: MIT-0

[libraries]
buildsrc-agp = { group = "com.android.tools.build", name = "gradle", version = "8.7.2" }
jna = { group = "net.java.dev.jna", name = "jna", version = "5.15.0" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.9.0" }
androidx-annotation = {group = "androidx.annotation", name = "annotation", version = "1.9.1"}
android-desugar = {group = "com.android.tools", name = "desugar_jdk_libs", version = "2.1.3" }

[plugins]
# agp already on cp from buildsrc -> specifying a version does not work
android-library = { id = "com.android.library" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.0.0" }
